services:
  invoices:
    image: postgres
    ports:
      - "5483:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=invoices
    volumes:
      - ./docker:/docker-entrypoint-initdb.d
